server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-petclinic/spring-petclinic-microservices-config
          default-label: main
        native:
          search-locations: file:///${GIT_REPO}

rox:
  key: "64595968-4a49-4f49-7ebd-b08938ad1d2e"
