apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
spec:
  template:
    spec:
      containers:
        - name: configserver
          image: caannamalai/configserver:3.2.4-staging
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: configserver-ingress
spec:
  rules:
    - host: 
      http:
        paths:
          - path: /config
            pathType: Prefix
            backend:
              service:
                name: configserver-service
                port:
                  number: 8888
