apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  workflow_dispatch:
jobs:
  Build:
    outputs:
      unitTestResults: ${{ steps.RunUnitTest.outputs.mvn_test_stdio1 }}
      commit_id: ${{ steps.commitinfo.outputs.commit_id }}
      commit_msg: ${{ steps.commitinfo.outputs.commit_msg }}
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Commit changes with JIRA key
        id: commit_changes
        uses: docker://alpine/git:latest
        run: |
          JIRA_KEY="CBDEMO-152"
          git add .
          git commit -m "$JIRA_KEY: Commit message describing changes"
          git push origin main
      - name: Get Commit Info
        uses: docker://alpine/git:latest
        id: commitinfo
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "commit_id=${COMMIT_ID}" >> $CLOUDBEES_OUTPUTS/commit_id
          echo "commit_msg=${COMMIT_MSG}" >> $CLOUDBEES_OUTPUTS/commit_msg
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install
  StaticAnalysis:
    outputs:
      BLOCKER_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.BLOCKER_COUNT }}
      CRITICAL_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.CRITICAL_COUNT }}
      MAJOR_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.MAJOR_COUNT }}
      MINOR_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.MINOR_COUNT }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Commit changes with JIRA key
        id: commit_changes
        uses: docker://alpine/git:latest
        run: |
          JIRA_KEY="CBDEMO-152"
          git add .
          git commit -m "$JIRA_KEY: Commit message describing changes"
          git push origin main
  ArtifactPublish:
    needs: Build
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Commit changes with JIRA key
        id: commit_changes
        uses: docker://alpine/git:latest
        run: |
          JIRA_KEY="CBDEMO-152"
          git add .
          git commit -m "$JIRA_KEY: Commit message describing changes"
          git push origin main
      - name: Publish to Nexus
        uses: docker://maven:3-eclipse-temurin-17
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          mvn deploy \
            -DaltDeploymentRepository=nexus::default::https://${NEXUS_USERNAME}:${NEXUS_PASSWORD}@nexus.cb-demos.io/repository/Petclinic/
