apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  ValidateCommits:
    steps:
      - name: Checkout Repository
        id: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Configure git
        id: info
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

          # Fetch more commits if needed
          git fetch --depth=10

          # Check if there is a previous commit to compare
          if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
            git log --pretty=format:"%s" HEAD~1..HEAD > commit_messages.txt
            echo "Comparing commit messages:"
            cat commit_messages.txt
          else
            echo "No previous commit found to compare. Skipping commit message validation." > commit_messages.txt
            # Optionally, exit with a status that indicates success if you want to skip validation for initial commits
            exit 0
          fi

          # Validate commit message
          grep -Eo 'CBDEMO-135' commit_messages.txt || (echo "Jira issue key missing in commit message" && exit 1)

  Build:
    needs: ValidateCommits
    steps:
      - name: Build
        id: Buildinfo
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          cd /cloudbees/workspace  # Ensure we are in the repository directory
          mvn clean install
