apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Build:
    steps:
      - uses: docker://alpine/git:latest
        name: Configure git
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: docker://maven:3-eclipse-temurin-17
        name: Build
        kind: build
        run: mvn clean test
        shell: sh
   
  dfg:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: cloudbees-io/snyk-sast-scan-code@v1
        name: fdf
        kind: scan
        with:
          orgname: ashok.alogicfocus
          token: 79781dde-8b3d-45c6-9561-a2ebc1e9e18c
          language: LANGUAGE_JAVA
 
  ddd:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: docker://maven:3-eclipse-temurin-17
        name: ded
        kind: build
        run: mvn clean package
        shell: sh
      - uses: docker://maven:3-eclipse-temurin-17
        name: jhgj
        kind: test
        run: mvn test
        shell: sh

      - name: Publish test results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: Junit
          folder-name: sample/test
