apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  pull_request:
    branches:
      - ashok
      - main

jobs:
  Build:
    
    steps:
      - name: Configure git
        id: info
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace


      - name: Checkout
        id: Buil
        uses: cloudbees-io/checkout@v1

      - name: Build
        id: Buildinfo
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install
