apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
 
  push:
    branches:
      - main
jobs:
  Build:
    steps:
      - name: Configure git
        id: config
        uses: docker://alpine/git:latest
        run: |
          git config --global user.email "c_aannamalai@cloudbees.com"
          git config --global user.name "cashokannamalai"
          git config --global --add safe.directory /cloudbees/workspace
      - name: Checkout
        id: configbuild
        uses: cloudbees-io/checkout@v1
      - name: Build
        id: build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install
      - name: Scan with GitHub Advanced Security
        uses: cloudbees-io/github-security-sast-scan-code@v1
        with:
          token: ${{ secrets.GITHUB_SECRET }}
          language: LANGUAGE_JAVA



      - name: SonarQube Scan
        id: sonar
        uses: docker://maven:3-eclipse-temurin-17
        env:
          SONAR_HOST_URL:  https://sonarqube.cb-demos.io
          SONAR_TOKEN:  ${{ secrets.token }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=config \
            -Dsonar.host.url= https://sonarqube.cb-demos.io \
            -Dsonar.login=token: ${{ secrets.token }}
            

