apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Jira-Enforced Workflow
on:
  push:
    branches:
      - main

jobs:
  PreCheck:
    steps:

      - name: Checkout Code
        uses: cloudbees-io/checkout@v1
        
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace

      - name: Check for Jira Issue Key
        uses: docker://alpine/git:latest
        run: |
          if ! git log -1 --pretty=%B | grep -qE 'JIRA-[0-9]+'; then
            echo "Error: Commit message must include a Jira issue key (e.g., JIRA-123)."
            exit 1
          fi

  Build:
    needs: PreCheck
    steps:
      - name: Checkout Code
        uses: cloudbees-io/checkout@v1

      - name: Build with Maven
        uses: docker://maven:3-eclipse-temurin-17
        run: mvn clean install
        shell: sh

  SonarQubeScan:
    needs: Build
    steps:
      - name: Checkout Code
        uses: cloudbees-io/checkout@v1

      - name: SonarQube Scan
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        with:
          sonar-exclusion: src/main/java
          cover-file-name: ./pom.xml
          language: "LANGUAGE_JAVA"
