apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My Automation
on:
  push:
    branches:
      - ashok
jobs:
  Checkout:
    steps:
      - name: Checkout Source Code
        uses: cloudbees-io/checkout@v1

  Build:
    needs: Checkout
    environment: sampleflag
    steps:
      - name: Configure Git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Build and Run Application
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean package
      - name: Run SonarQube Analysis
        uses: docker://sonarsource/sonar-scanner-cli:latest
        run: |
          sonar-scanner \
            -Dsonar.projectKey=spring-petclinic-config-server \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarqube.cb-demos.io \
            -Dsonar.login=${{ secrets.token }}
      - name: Get Vulnerability Report
        uses: docker://alpine/git:latest
        run: |
          # Fetch the latest analysis report
          curl -X GET "https://sonarqube.cb-demos.io/api/issues/search?componentKeys=spring-petclinic-config-server" \
            -H "Authorization: Bearer $SONARQUBE_TOKEN" \
            | jq '.total' > total_vulnerabilities.txt
          curl -X GET "https://sonarqube.cb-demos.io/api/issues/search?componentKeys=spring-petclinic-config-server&statuses=OPEN" \
            -H "Authorization: Bearer $SONARQUBE_TOKEN" \
            | jq '.total' > open_vulnerabilities.txt
          curl -X GET "https://sonarqube.cb-demos.io/api/issues/search?componentKeys=spring-petclinic-config-server&statuses=REOPENED" \
            -H "Authorization: Bearer $SONARQUBE_TOKEN" \
            | jq '.total' > reopened_vulnerabilities.txt
          curl -X GET "https://sonarqube.cb-demos.io/api/issues/search?componentKeys=spring-petclinic-config-server&statuses=RESOLVED" \
            -H "Authorization: Bearer $SONARQUBE_TOKEN" \
            | jq '.total' > resolved_vulnerabilities.txt
