apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Build:
    steps:
      - name: Configure git
        id: config
        uses: docker://alpine/git:latest
        run: |
          git config --global user.email "c_aannamalai@cloudbees.com"
          git config --global user.name "cashokannamalai"
          git config --global --add safe.directory /cloudbees/workspace

      - name: Checkout
        id: configbuild
        uses: cloudbees-io/checkout@v1
      
      - name: Build
        id: build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install

      - name: Commit changes with JIRA key
        id: commit_changes
        uses: docker://alpine/git:latest
        run: |
          JIRA_KEY="CBDEMO-152"
          git add .
          git commit -m "$JIRA_KEY: Commit message describing changes"
          git push origin main
