apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    environment: production
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - uses: cloudbees-io/cbci-run-job@v2
        name: CBCI Deploy
        with:
          url: https://sda.preview.cb-demos.io/ashok-petclinic/
          username: c_aannamalai
          token: ${{ secrets.SNAQVI_CI_TOKEN }}
          job-name: spring-petclinic/job/spring-petclinic-config-server
          test-type: Junit
          test-result-location: testReport
  Build23:
    needs: build-deploy
    environment: production
    steps:
      - uses: cloudbees-io/cbci-run-job@v2
        name: stpes1
        kind: deploy
        with:
          url: https://sda.preview.cb-demos.io/ashok-petclinic/
          username: c_aannamalai
          token: ${{ secrets.SNAQVI_CI_TOKEN }}
          job-name: spring-petclinic/job/spring-petclinic-config-server
  sample:
    environment: production
    needs: Build23
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - uses: cloudbees-io/kustomize-deploy@v1
        name: deploy
        kind: deploy
        with:
          kustomization-base-dir: /cloudbees/workspace/base
