apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Build:
    steps:
      - uses: docker://alpine/git:latest
        name: Configure git
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: docker://maven:3-eclipse-temurin-17
        name: Build
        kind: build
        run: mvn clean test
        shell: sh
   
  samole:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        name: sample
        kind: scan
        with:
          sonar-inclusion: src/test/java
          sonar-exclusion: src/main/java
          cover-file-name: ./pom.xml
          language: LANGUAGE_JAVA
