apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
 
  push:
    branches:
      - main
jobs:
  build-test:
    steps:
     
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      
      - uses: docker://maven:3-eclipse-temurin-17
        name: Maven Build
        shell: sh
        run: |
          mvn clean test

      - name: Scan with SonarQube bundled
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        with:
          sonar-exclusion: sonar/*
          cover-file-name: ./coverage.xml
          language: LANGUAGE_JAVA
      



    

