apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My Automation
on:
  push:
    branches:
      - main
jobs:
  CheckCommitMessage:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
  Build:
    needs: CheckCommitMessage
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: mvn clean install
