apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Buildsample:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - uses: docker://maven:3-eclipse-temurin-17
        name: Build1
        kind: build
        run: mvn clean package
        shell: sh
  Scan:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        name: scan
        kind: scan
        with:
          language: LANGUAGE_JAVA
          cover-file-name: pom.xml
          sonar-exclusion: src/main/java
