apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - ashok
jobs:
  Build:
    outputs:
      unitTestResults: ${{ steps.RunUnitTest.outputs.mvn_test_stdio1 }}
      commit_id: ${{ steps.commitinfo.outputs.commit_id }}
      commit_msg: ${{ steps.commitinfo.outputs.commit_msg }}
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace



      - name: Checkout
        uses: cloudbees-io/checkout@v1


      - name: Get Commit Info
        uses: docker://alpine/git:latest
        id: commitinfo
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "commit_id=${COMMIT_ID}" >> $CLOUDBEES_OUTPUTS/commit_id
          echo "commit_msg=${COMMIT_MSG}" >> $CLOUDBEES_OUTPUTS/commit_msg



      

      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install

          
      - name: RunUnitTest
        id: RunUnitTest
        uses: docker://maven:3-eclipse-temurin-17
        run: >
          mvn test > "$CLOUDBEES_OUTPUTS/mvn_test_stdio"

          cat "$CLOUDBEES_OUTPUTS/mvn_test_stdio" | grep "Tests run:" | tail -1
          > "$CLOUDBEES_OUTPUTS/mvn_test_stdio1"
  StaticAnalysis:
    needs: Build
    steps:
      - name: Checkout Source Code
        uses: cloudbees-io/checkout@v1
      - name: Scan with GitHub Advanced Security
        uses: cloudbees-io/github-security-sast-scan-code@v1
        with:
          token: ${{ secrets.GITHUB_SECRET }}
          language: LANGUAGE_JAVA
      - name: SonarQube Scan
        uses: docker://maven:3-eclipse-temurin-17
        env:
          SONAR_TOKEN: ${{ secrets.token }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=spring-petclinic-config-server \
            -Dsonar.host.url=https://sonarqube.cb-demos.io \
            -Dsonar.login=${SONAR_TOKEN}
      - name: Scan with SonarQube bundled action
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1


      - name: Run Octopus Deploy
        uses: cloudbees-io/octopus-run-project@v2
        with:
          url: https://vimanthan.octopus.app/
          token: API-GSXA89ARJYZ5L8SUV4IMUL5JG2REALO
          space-name: Default
          release: 1.0.0
          environment-name: Development
          channel-name: Default

        

