apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Jira-Enforced Workflow
on:
  push:
    branches:
      - main

jobs:
  CheckCommitMessage:
  
    steps:
      - name: Checkout Code
        uses: cloudbees-io/checkout@v1
        
      - name: Check Commit Message
        uses: docker://alpine/git:latest
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if ! [[ "$COMMIT_MESSAGE" =~ ^CBDEMO-[0-9]+ ]]; then
            echo "Commit message must include a valid Jira issue key (e.g., CBDEMO-122)."
            exit 1
          fi

  Build:
    needs: CheckCommitMessage
    steps:
      - name: Checkout Code
        uses: cloudbees-io/checkout@v1

      - name: Build with Maven
        uses: docker://maven:3-eclipse-temurin-17
        run: mvn clean install
        shell: sh

  SonarQubeScan:
    needs: Build
    steps:
      - name: Checkout Code
        uses: cloudbees-io/checkout@v1
      - name: SonarQube Scan
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        with:
          sonar-exclusion: "src/main/java/**"
          cover-file-name: "./pom.xml"
          language: "LANGUAGE_JAVA"
