apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Build:
    outputs:
      unitTestResults: ${{ steps.RunUnitTest.outputs.mvn_test_stdio1 }}
      commit_id: ${{ steps.commitinfo.outputs.commit_id }}
      commit_msg: ${{ steps.commitinfo.outputs.commit_msg }}
    steps:
      - name: Configure git
        id: config
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
          git config --global user.email "c_aannamalai@cloudbees.com"
          git config --global user.name "cashokannamalai"
      - name: Checkout
        id: configbuild
        uses: cloudbees-io/checkout@v1
      - name: Get Commit Info
        uses: docker://alpine/git:latest
        id: commitinfo
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "commit_id=${COMMIT_ID}" >> $CLOUDBEES_OUTPUTS/commit_id
          echo "commit_msg=${COMMIT_MSG}" >> $CLOUDBEES_OUTPUTS/commit_msg
      - name: Add JIRA Key to Commit Message
        id: add
        uses: docker://alpine/git:latest
        run: |
          JIRA_KEY="CBDEMO-124"  
          NEW_COMMIT_MSG="${JIRA_KEY}: ${COMMIT_MSG}"
          git commit --amend -m "$NEW_COMMIT_MSG"
      - name: Build
        id: build
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn clean install
