apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Build:
   
    steps:
      - name: Configure git
        uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: Checkout
        uses: cloudbees-io/checkout@v1
    
      - uses: docker://maven:3-eclipse-temurin-17
        name: Build
        kind: build
        run: mvn clean package
        shell: sh
    



  StaticAnalysis:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1


      - name: Scan with GitHub Advanced Security
        uses: cloudbees-io/github-security-sast-scan-code@v1
        with:
          token: ${{ secrets.GITHUB_SECRET }}
          language: "LANGUAGE_JAVA"
          branch-name: "main"



      - uses: cloudbees-io/sonarqube-sast-scan-code@v1
        name: Scan
        kind: scan
        with:
          server-url: https://sonarqube.cb-demos.io
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          language: LANGUAGE_JAVA


      - name: Scan with SonarQube bundled
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        with:
          sonar-exclusion: src/main/java
          cover-file-name: /.pom.xml
          language: LANGUAGE_JAVA
     
        
  SonarScan:
    needs: Build
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Run SonarQube analysis
        uses: docker://maven:3-eclipse-temurin-17
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=config-server \
            -Dsonar.host.url=https://sonarqube.cb-demos.io \
            -Dsonar.login=${{ secrets.token }}
     
  sample:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - uses: docker://maven:3-eclipse-temurin-17
        name: test
        kind: test
        run: mvn test
        shell: sh
