apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  sample:
    environment: production
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - uses: cashokannamalai/kubeconfig@v1
        name: Set kubeconfig
        with:
          secname: ${{ secrets.kubeconfig }}

      - uses: cloudbees-io/kustomize-deploy@v1
        name: deploy
        kind: deploy
        with:
          kustomization-base-dir: ${{ cloudbees.workspace }}/base
