apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - main
jobs:
  Buildsample:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - uses: docker://maven:3-eclipse-temurin-17
        name: Build1
        kind: build
        run: mvn clean package
        shell: sh
  sacn1:
    steps:
      - uses: cloudbees-io/publish-test-results@v1
        name: scan
        kind: test
        with:
          test-type: TESTING
          folder-name: pom.xml
