apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My Automation
on:
  push:
    branches:
      - main
jobs:
  CheckCommitMessage:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Check for Jira issue key in commit message
        uses: docker://alpine/git:latest
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if ! echo "$COMMIT_MESSAGE" | grep -E '[A-Z]{2,}-[0-9]+'; then
            echo "Error: Commit message must include a Jira issue key (e.g., PROJECT-123)."
            exit 1
          fi

  Build:
    needs: CheckCommitMessage
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://maven:3-eclipse-temurin-17
        run: mvn clean install
      - name: Scan with SonarQube bundled
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        with:
          sonar-exclusion: src/main/java
          cover-file-name: ./pom.xml
          language: LANGUAGE_JAVA

          